#!/usr/bin/env python
"""Seed a ready-to-explore demo space (SA-104).

Creates a "ScholarAI Demo" space with a real ingested primer document, a curated
concept graph, coverage, and a spread of quiz events — so a first-time user sees
the concept map, prerequisite edges, and *demonstrated mastery* (mastered /
learning / weak buckets, a misconception, a review-due concept) immediately,
without needing Ollama or uploading anything.

Everything here is deterministic and offline: ingestion runs the real pipeline
(local embeddings), and concepts/events are written straight to disk rather than
generated by the LLM.

Usage (from the repo root)::

    ./backend/.venv/bin/python scripts/seed_demo.py           # skip if it exists
    ./backend/.venv/bin/python scripts/seed_demo.py --force    # recreate it
"""

from __future__ import annotations

import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Make the backend package importable when run from the repo root.
BACKEND = Path(__file__).resolve().parent.parent / "backend"
sys.path.insert(0, str(BACKEND))

from app import storage  # noqa: E402
from app.services import documents, progress, spaces, vectorstore  # noqa: E402
from app.services.spaces import SpaceExists, SpaceNotFound  # noqa: E402

SPACE_NAME = "ScholarAI Demo"
SPACE_ID = "scholarai-demo"

PRIMER = """# Vector Search & RAG — A Short Primer

## Embeddings
An embedding maps text (or images) into a dense vector of floating-point numbers
so that semantically similar items land close together in vector space. Modern
retrieval systems embed both documents and queries with the same model, then
compare vectors to find relevant content. Good embeddings capture meaning, not
just surface words.

## Vector Search
Vector search finds the items whose embeddings are nearest to a query embedding,
usually by cosine similarity. Unlike keyword search it can match paraphrases and
synonyms because it operates on meaning. A vector database stores the vectors and
serves nearest-neighbor queries efficiently.

## Approximate Nearest Neighbor
Exact nearest-neighbor search is too slow at scale, so approximate nearest
neighbor (ANN) algorithms trade a little recall for a large speed-up. They build
an index over the vectors that lets a query skip most comparisons while still
finding almost all of the true neighbors.

## HNSW
HNSW (Hierarchical Navigable Small World) is a graph-based ANN index. It builds a
layered proximity graph and greedily walks from an entry point toward the query,
giving high recall at low latency. It is a common default index for vector
databases.

## Product Quantization
Product quantization compresses vectors by splitting each into sub-vectors and
replacing each sub-vector with the id of a nearby centroid. This shrinks the index
dramatically so huge collections fit in memory, at the cost of some precision.

## Retrieval-Augmented Generation
Retrieval-augmented generation (RAG) grounds a language model's answer in
retrieved context: embed the question, run vector search to fetch relevant
chunks, and pass them to the model as evidence. This reduces hallucination and
lets the model cite sources it was never trained on.
"""

# Curated concept graph: id -> (label, prerequisite ids, keywords for section map).
CONCEPTS = {
    "embeddings": ("Embeddings", [], ["embedding"]),
    "vector-search": ("Vector Search", [], ["vector search", "vector database"]),
    "approximate-nearest-neighbor": (
        "Approximate Nearest Neighbor", ["vector-search"], ["approximate nearest", "ann"],
    ),
    "hnsw": ("HNSW", ["approximate-nearest-neighbor"], ["hnsw"]),
    "product-quantization": (
        "Product Quantization", ["vector-search"], ["product quantization", "quantiz"],
    ),
    "retrieval-augmented-generation": (
        "Retrieval-Augmented Generation", ["embeddings", "vector-search"], ["retrieval-augmented", "rag"],
    ),
}


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _event(concept_id, qtype, correct, score, confidence, days_ago, *, misconception=None):
    ts = (_now() - timedelta(days=days_ago)).isoformat()
    return {
        "event_id": f"seed-{concept_id}-{qtype}",
        "ts": ts,
        "concept_id": concept_id,
        "type": qtype,
        "source": "quiz",
        "question": f"(demo) {qtype} question about {concept_id}",
        "answer": "(demo answer)",
        "correct": correct,
        "score": score,
        "confidence": confidence,
        "misconception": misconception,
        "misconception_flag": (not correct) and confidence >= 4,
        "retrieval_confidence": None,
        "prompt_version": "seed",
    }


# A spread designed to show every bucket + a misconception + a review-due concept.
EVENTS = [
    # Vector Search — freshly mastered
    _event("vector-search", "recall", True, 88, 4, 1),
    _event("vector-search", "recognition", True, 100, 5, 1),
    _event("vector-search", "application", True, 90, 4, 1),
    # Embeddings — learning
    _event("embeddings", "recall", True, 60, 3, 2),
    _event("embeddings", "recognition", True, 100, 4, 2),
    # ANN — weak, with a confident-but-wrong misconception
    _event("approximate-nearest-neighbor", "recall", False, 30, 2, 3),
    _event(
        "approximate-nearest-neighbor", "recognition", False, 0, 5, 3,
        misconception="Believes ANN returns exact nearest neighbors",
    ),
    # HNSW — mastered long ago → retention decayed → review due
    _event("hnsw", "recall", True, 90, 5, 26),
    _event("hnsw", "recognition", True, 100, 5, 26),
    _event("hnsw", "application", True, 88, 4, 26),
    # RAG — learning
    _event("retrieval-augmented-generation", "recall", True, 72, 4, 2),
    # Product Quantization — encountered but never quizzed → stays "untested"
]


def _section_concepts(space_id: str) -> tuple[dict, dict]:
    """Map curated concepts onto the real ingested sections by keyword."""
    sections = vectorstore.load_all_sections(space_id)
    concepts: dict[str, dict] = {}
    section_concepts: dict[str, list[str]] = {sid: [] for sid in sections}

    for cid, (label, prereqs, keywords) in CONCEPTS.items():
        source_sections = [
            sid for sid, sec in sections.items()
            if any(k in sec.get("text", "").lower() for k in keywords)
        ]
        if not source_sections and sections:
            source_sections = [next(iter(sections))]  # never leave a concept orphaned
        concepts[cid] = {
            "id": cid,
            "label": label,
            "source_sections": source_sections,
            "prerequisites": prereqs,
        }
        for sid in source_sections:
            section_concepts.setdefault(sid, []).append(cid)
    return concepts, section_concepts


def main() -> int:
    force = "--force" in sys.argv
    try:
        spaces.get_space(SPACE_ID)
        if not force:
            print(f"✓ Demo space {SPACE_ID!r} already exists — pass --force to recreate.")
            return 0
        spaces.delete_space(SPACE_ID)
        print(f"→ Removed existing {SPACE_ID!r} (--force).")
    except SpaceNotFound:
        pass

    try:
        space = spaces.create_space(SPACE_NAME)
    except SpaceExists:
        # Name collided but id differs; fall back to the canonical id.
        space = spaces.get_space(SPACE_ID)
    print(f"→ Created space {space.id!r} ({space.name}).")

    doc = documents.save_and_ingest(space.id, "vector-search-primer.md", PRIMER.encode())
    print(f"→ Ingested {doc.name} → {doc.chunk_count} chunks (real embeddings).")

    concepts, section_concepts = _section_concepts(space.id)
    storage.write_json(
        storage.space_layout(space.id)["concepts"],
        {
            "concepts": concepts,
            "section_concepts": section_concepts,
            "extracted_at": _now().isoformat(),
            "prompt_version": "seed",
        },
    )
    print(f"→ Wrote {len(concepts)} concepts + prerequisite graph.")

    # Coverage: every concept has been encountered.
    progress.mark_encountered(space.id, list(concepts))

    events_path = storage.space_layout(space.id)["events"]
    for ev in EVENTS:
        storage.append_jsonl(events_path, ev)
    print(f"→ Wrote {len(EVENTS)} quiz events (mastered / learning / weak + a misconception + a review-due concept).")

    print(
        f"\n✓ Done. Open the app and pick “{SPACE_NAME}” — the Dashboard shows the "
        "concept graph and demonstrated mastery straight away."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
